### ISSUE TITLE
Assembly error

### ISSUE THREAD

**Issue by themikestrikes** [PachydermAcoustic/PachydermAcoustic_Rhinoceros#7]
Hi,

After found all dependencies for the project it seems that something is still missing.
For istance, there's a point where an element ".Wave" is called from the Pach_SP file in the Universal assembly, 
but there are no kind of properties/methods in the project (70 errors like that in the code). Maybe it is a modded version updated on git hub by error?

![wave](https://user-images.githubusercontent.com/92297573/136759546-073808ef-510f-4e68-a422-164c057b97bf.PNG)

Thank You!

**Comment by AvdHarten** [comment]
No. Pach_SP should be in the repository, as it does most of the signal processing on the project. I'll try to figure out why it isn't copying.
Arthur

**Comment by themikestrikes** [comment]
Or maybe i missed something..
However, thank you! 
Waiting for the results!

**Comment by AvdHarten** [comment]
I figured it out. You are looking at a file in one branch, and referencing the Pach_SP file from a different branch. I just checked, and the files are consistent.
